'use strict';

mdrSearchApp.controller('SearchController',
    function SearchController($scope, $route, dataProvider) {


        var data = [{
            "memberName": "Cox",
            "callDate": "11/11/2015",
            "callerFirstName": "Jack",
            "callerLastName": "Nicholson",
            "callerRelationship": "brother",
            "callStatus": "successfull",
            "callerPhoneNumber": "111-111-111",
            "callDuration": "100",
            "callType": "Any type",
            "anotherCallProperty": "info"
        }, {
            "memberName": "Steve",
            "callDate": "12/11/2015",
            "callerFirstName": "Raplh",
            "callerLastName": "Fiennes",
            "callerRelationship": "uncle",
            "callStatus": "successfull",
            "callerPhoneNumber": "111-333-111",
            "callDuration": "89",
            "callType": "Any type",
            "anotherCallProperty": "info"
        },{
            "memberName": "Sam",
            "callDate": "10/10/2015",
            "callerFirstName": "Daniel",
            "callerLastName": "Day-Lewis",
            "callerRelationship": "brother",
            "callStatus": "unsuccessfull",
            "callerPhoneNumber": "789-111-111",
            "callDuration": "0",
            "callType": "Any type",
            "anotherCallProperty": "info"
        },{
            "memberName": "Roy",
            "callDate": "11/09/2015",
            "callerFirstName": "Robert",
            "callerLastName": "De Niro",
            "callerRelationship": "brother",
            "callStatus": "successfull",
            "callerPhoneNumber": "111-456-111",
            "callDuration": "100",
            "callType": "Any type",
            "anotherCallProperty": "info"
        },{
            "memberName": "Me",
            "callDate": "11/11/2015",
            "callerFirstName": "Al",
            "callerLastName": "Pacino",
            "callerRelationship": "friend",
            "callStatus": "successfull",
            "callerPhoneNumber": "111-101-000",
            "callDuration": "420",
            "callType": "Any type",
            "anotherCallProperty": "info"
        },{
            "memberName": "John",
            "callDate": "03/05/2015",
            "callerFirstName": "Dustin",
            "callerLastName": "Hoffman",
            "callerRelationship": "friend",
            "callStatus": "successfull",
            "callerPhoneNumber": "123-456-789",
            "callDuration": "555",
            "callType": "Any type",
            "anotherCallProperty": "info"
        },{
            "memberName": "Carl",
            "callDate": "12/12/2015",
            "callerFirstName": "Brad",
            "callerLastName": "Pitt",
            "callerRelationship": "classMate",
            "callStatus": "successfull",
            "callerPhoneNumber": "131-313",
            "callDuration": "421",
            "callType": "Any type",
            "anotherCallProperty": "info"
        },{
            "memberName": "Rob",
            "callDate": "11/11/2015",
            "callerFirstName": "Anthony",
            "callerLastName": "Hopkins",
            "callerRelationship": "unknown",
            "callStatus": "successfull",
            "callerPhoneNumber": "100-000-000",
            "callDuration": "892",
            "callType": "Any type",
            "anotherCallProperty": "info"
        },{
            "memberName": "Linda",
            "callDate": "11/12/2015",
            "callerFirstName": "Marlon",
            "callerLastName": "Brando",
            "callerRelationship": "daughter",
            "callStatus": "successfull",
            "callerPhoneNumber": "1345611",
            "callDuration": "9547",
            "callType": "Any type",
            "anotherCallProperty": "info"
        },{
            "memberName": "Tim",
            "callDate": "10/10/2015",
            "callerFirstName": "Jeremy",
            "callerLastName": "Irons",
            "callerRelationship": "brother",
            "callStatus": "successfull",
            "callerPhoneNumber": "551-111-111",
            "callDuration": "88",
            "callType": "Any type",
            "anotherCallProperty": "info"
        },{
            "memberName": "Sammy",
            "callDate": "11/08/2015",
            "callerFirstName": "Denzel",
            "callerLastName": "Washington",
            "callerRelationship": "brother",
            "callStatus": "unsuccessfull",
            "callerPhoneNumber": "111-111-444",
            "callDuration": "0",
            "callType": "Any type",
            "anotherCallProperty": "info"
        },{
            "memberName": "Adam",
            "callDate": "11/11/2015",
            "callerFirstName": "Gene",
            "callerLastName": "Hackman",
            "callerRelationship": "brother",
            "callStatus": "successfull",
            "callerPhoneNumber": "111-111-111",
            "callDuration": "100",
            "callType": "Any type",
            "anotherCallProperty": "info"
        },{
            "memberName": "Rooney",
            "callDate": "11/11/2015",
            "callerFirstName": "Jeff",
            "callerLastName": "Bridges",
            "callerRelationship": "brother",
            "callStatus": "successfull",
            "callerPhoneNumber": "NUMBER",
            "callDuration": "100",
            "callType": "Any type",
            "anotherCallProperty": "info"
        },{
            "memberName": "Alex",
            "callDate": "05/11/2015",
            "callerFirstName": "Tim",
            "callerLastName": "Robins",
            "callerRelationship": "brother",
            "callStatus": "successfull",
            "callerPhoneNumber": "111-111-111",
            "callDuration": "100",
            "callType": "Any type",
            "anotherCallProperty": "info"
        },{
            "memberName": "Alexey",
            "callDate": "11/11/2015",
            "callerFirstName": "Henry",
            "callerLastName": "Fonda",
            "callerRelationship": "brother",
            "callStatus": "successfull",
            "callerPhoneNumber": "111-111-111",
            "callDuration": "100",
            "callType": "Any type",
            "anotherCallProperty": "info"
        },{
            "memberName": "Kelly",
            "callDate": "11/11/2015",
            "callerFirstName": "William",
            "callerLastName": "Hurt",
            "callerRelationship": "sister",
            "callStatus": "successfull",
            "callerPhoneNumber": "111-4345-111",
            "callDuration": "100",
            "callType": "Any type",
            "anotherCallProperty": "info"
        },{
            "memberName": "Zlatan",
            "callDate": "11/11/2015",
            "callerFirstName": "Kevin",
            "callerLastName": "Costner",
            "callerRelationship": "friend",
            "callStatus": "successfull",
            "callerPhoneNumber": "111-111-111",
            "callDuration": "100",
            "callType": "Any type",
            "anotherCallProperty": "info"
        },{
            "memberName": "Clint",
            "callDate": "11/11/2015",
            "callerFirstName": "Clint",
            "callerLastName": "Eastwood",
            "callerRelationship": "same",
            "callStatus": "successfull",
            "callerPhoneNumber": "111-111-111",
            "callDuration": "100",
            "callType": "Any type",
            "anotherCallProperty": "info"
        },{
            "memberName": "Santa Claus",
            "callDate": "11/11/2015",
            "callerFirstName": "Leonardo",
            "callerLastName": "DiCaprio",
            "callerRelationship": "grandpa",
            "callStatus": "successfull",
            "callerPhoneNumber": "111-111-111",
            "callDuration": "100",
            "callType": "Any type",
            "anotherCallProperty": "info"
        },{
            "memberName": "No name",
            "callDate": "11/11/2015",
            "callerFirstName": "Mel",
            "callerLastName": "Gibson",
            "callerRelationship": "brother",
            "callStatus": "successfull",
            "callerPhoneNumber": "111-111-111",
            "callDuration": "6787",
            "callType": "Any type",
            "anotherCallProperty": "info"
        }];

        var dataWithMoreProperties = [{
            "memberName": "Cox",
            "callDate": "11/11/2015",
            "callerFirstName": "Jack",
            "callerLastName": "Nicholson",
            "callerRelationship": "brother",
            "callStatus": "successfull",
            "callerPhoneNumber": "111-111-111",
            "callDuration": "100",
            "callType": "Any type",
            "anotherCallProperty": "info",
            "additionalProperty1": "1",
            "additionalProperty2": "2",
            "additionalProperty3": "3",
            "additionalProperty4": "4",
            "additionalProperty5": "5",
            "additionalProperty6": "6",
            "additionalProperty7": "7",
            "additionalProperty8": "8",
            "additionalProperty9": "9",
            "additionalProperty10": "10",
            "additionalProperty11": "11",
            "additionalProperty12": "12",
            "additionalProperty13": "13",
            "additionalProperty14": "14",
            "additionalProperty15": "15",
            "additionalProperty16": "16",
            "additionalProperty17": "17",
            "additionalProperty18": "18",
            "additionalProperty19": "19",
            "additionalProperty20": "20"
        }, {
            "memberName": "Steve",
            "callDate": "12/11/2015",
            "callerFirstName": "Raplh",
            "callerLastName": "Fiennes",
            "callerRelationship": "uncle",
            "callStatus": "successfull",
            "callerPhoneNumber": "111-333-111",
            "callDuration": "89",
            "callType": "Any type",
            "anotherCallProperty": "info",
            "additionalProperty1": "1",
            "additionalProperty2": "2",
            "additionalProperty3": "3",
            "additionalProperty4": "4",
            "additionalProperty5": "5",
            "additionalProperty6": "6",
            "additionalProperty7": "7",
            "additionalProperty8": "8",
            "additionalProperty9": "9",
            "additionalProperty10": "10",
            "additionalProperty11": "11",
            "additionalProperty12": "12",
            "additionalProperty13": "13",
            "additionalProperty14": "14",
            "additionalProperty15": "15",
            "additionalProperty16": "16",
            "additionalProperty17": "17",
            "additionalProperty18": "18",
            "additionalProperty19": "19",
            "additionalProperty20": "20"
        },{
            "memberName": "Sam",
            "callDate": "10/10/2015",
            "callerFirstName": "Daniel",
            "callerLastName": "Day-Lewis",
            "callerRelationship": "brother",
            "callStatus": "unsuccessfull",
            "callerPhoneNumber": "789-111-111",
            "callDuration": "0",
            "callType": "Any type",
            "anotherCallProperty": "info",
            "additionalProperty1": "1",
            "additionalProperty2": "2",
            "additionalProperty3": "3",
            "additionalProperty4": "4",
            "additionalProperty5": "5",
            "additionalProperty6": "6",
            "additionalProperty7": "7",
            "additionalProperty8": "8",
            "additionalProperty9": "9",
            "additionalProperty10": "10",
            "additionalProperty11": "11",
            "additionalProperty12": "12",
            "additionalProperty13": "13",
            "additionalProperty14": "14",
            "additionalProperty15": "15",
            "additionalProperty16": "16",
            "additionalProperty17": "17",
            "additionalProperty18": "18",
            "additionalProperty19": "19",
            "additionalProperty20": "20"
        },{
            "memberName": "Roy",
            "callDate": "11/09/2015",
            "callerFirstName": "Robert",
            "callerLastName": "De Niro",
            "callerRelationship": "brother",
            "callStatus": "successfull",
            "callerPhoneNumber": "111-456-111",
            "callDuration": "100",
            "callType": "Any type",
            "anotherCallProperty": "info",
            "additionalProperty1": "1",
            "additionalProperty2": "2",
            "additionalProperty3": "3",
            "additionalProperty4": "4",
            "additionalProperty5": "5",
            "additionalProperty6": "6",
            "additionalProperty7": "7",
            "additionalProperty8": "8",
            "additionalProperty9": "9",
            "additionalProperty10": "10",
            "additionalProperty11": "11",
            "additionalProperty12": "12",
            "additionalProperty13": "13",
            "additionalProperty14": "14",
            "additionalProperty15": "15",
            "additionalProperty16": "16",
            "additionalProperty17": "17",
            "additionalProperty18": "18",
            "additionalProperty19": "19",
            "additionalProperty20": "20"
        },{
            "memberName": "Me",
            "callDate": "11/11/2015",
            "callerFirstName": "Al",
            "callerLastName": "Pacino",
            "callerRelationship": "friend",
            "callStatus": "successfull",
            "callerPhoneNumber": "111-101-000",
            "callDuration": "420",
            "callType": "Any type",
            "anotherCallProperty": "info",
            "additionalProperty1": "1",
            "additionalProperty2": "2",
            "additionalProperty3": "3",
            "additionalProperty4": "4",
            "additionalProperty5": "5",
            "additionalProperty6": "6",
            "additionalProperty7": "7",
            "additionalProperty8": "8",
            "additionalProperty9": "9",
            "additionalProperty10": "10",
            "additionalProperty11": "11",
            "additionalProperty12": "12",
            "additionalProperty13": "13",
            "additionalProperty14": "14",
            "additionalProperty15": "15",
            "additionalProperty16": "16",
            "additionalProperty17": "17",
            "additionalProperty18": "18",
            "additionalProperty19": "19",
            "additionalProperty20": "20"
        },{
            "memberName": "John",
            "callDate": "03/05/2015",
            "callerFirstName": "Dustin",
            "callerLastName": "Hoffman",
            "callerRelationship": "friend",
            "callStatus": "successfull",
            "callerPhoneNumber": "123-456-789",
            "callDuration": "555",
            "callType": "Any type",
            "anotherCallProperty": "info",
            "additionalProperty1": "1",
            "additionalProperty2": "2",
            "additionalProperty3": "3",
            "additionalProperty4": "4",
            "additionalProperty5": "5",
            "additionalProperty6": "6",
            "additionalProperty7": "7",
            "additionalProperty8": "8",
            "additionalProperty9": "9",
            "additionalProperty10": "10",
            "additionalProperty11": "11",
            "additionalProperty12": "12",
            "additionalProperty13": "13",
            "additionalProperty14": "14",
            "additionalProperty15": "15",
            "additionalProperty16": "16",
            "additionalProperty17": "17",
            "additionalProperty18": "18",
            "additionalProperty19": "19",
            "additionalProperty20": "20"
        },{
            "memberName": "Carl",
            "callDate": "12/12/2015",
            "callerFirstName": "Brad",
            "callerLastName": "Pitt",
            "callerRelationship": "classMate",
            "callStatus": "successfull",
            "callerPhoneNumber": "131-313",
            "callDuration": "421",
            "callType": "Any type",
            "anotherCallProperty": "info",
            "additionalProperty1": "1",
            "additionalProperty2": "2",
            "additionalProperty3": "3",
            "additionalProperty4": "4",
            "additionalProperty5": "5",
            "additionalProperty6": "6",
            "additionalProperty7": "7",
            "additionalProperty8": "8",
            "additionalProperty9": "9",
            "additionalProperty10": "10",
            "additionalProperty11": "11",
            "additionalProperty12": "12",
            "additionalProperty13": "13",
            "additionalProperty14": "14",
            "additionalProperty15": "15",
            "additionalProperty16": "16",
            "additionalProperty17": "17",
            "additionalProperty18": "18",
            "additionalProperty19": "19",
            "additionalProperty20": "20"
        },{
            "memberName": "Rob",
            "callDate": "11/11/2015",
            "callerFirstName": "Anthony",
            "callerLastName": "Hopkins",
            "callerRelationship": "unknown",
            "callStatus": "successfull",
            "callerPhoneNumber": "100-000-000",
            "callDuration": "892",
            "callType": "Any type",
            "anotherCallProperty": "info",
            "additionalProperty1": "1",
            "additionalProperty2": "2",
            "additionalProperty3": "3",
            "additionalProperty4": "4",
            "additionalProperty5": "5",
            "additionalProperty6": "6",
            "additionalProperty7": "7",
            "additionalProperty8": "8",
            "additionalProperty9": "9",
            "additionalProperty10": "10",
            "additionalProperty11": "11",
            "additionalProperty12": "12",
            "additionalProperty13": "13",
            "additionalProperty14": "14",
            "additionalProperty15": "15",
            "additionalProperty16": "16",
            "additionalProperty17": "17",
            "additionalProperty18": "18",
            "additionalProperty19": "19",
            "additionalProperty20": "20"
        },{
            "memberName": "Linda",
            "callDate": "11/12/2015",
            "callerFirstName": "Marlon",
            "callerLastName": "Brando",
            "callerRelationship": "daughter",
            "callStatus": "successfull",
            "callerPhoneNumber": "1345611",
            "callDuration": "9547",
            "callType": "Any type",
            "anotherCallProperty": "info",
            "additionalProperty1": "1",
            "additionalProperty2": "2",
            "additionalProperty3": "3",
            "additionalProperty4": "4",
            "additionalProperty5": "5",
            "additionalProperty6": "6",
            "additionalProperty7": "7",
            "additionalProperty8": "8",
            "additionalProperty9": "9",
            "additionalProperty10": "10",
            "additionalProperty11": "11",
            "additionalProperty12": "12",
            "additionalProperty13": "13",
            "additionalProperty14": "14",
            "additionalProperty15": "15",
            "additionalProperty16": "16",
            "additionalProperty17": "17",
            "additionalProperty18": "18",
            "additionalProperty19": "19",
            "additionalProperty20": "20"
        },{
            "memberName": "Tim",
            "callDate": "10/10/2015",
            "callerFirstName": "Jeremy",
            "callerLastName": "Irons",
            "callerRelationship": "brother",
            "callStatus": "successfull",
            "callerPhoneNumber": "551-111-111",
            "callDuration": "88",
            "callType": "Any type",
            "anotherCallProperty": "info",
            "additionalProperty1": "1",
            "additionalProperty2": "2",
            "additionalProperty3": "3",
            "additionalProperty4": "4",
            "additionalProperty5": "5",
            "additionalProperty6": "6",
            "additionalProperty7": "7",
            "additionalProperty8": "8",
            "additionalProperty9": "9",
            "additionalProperty10": "10",
            "additionalProperty11": "11",
            "additionalProperty12": "12",
            "additionalProperty13": "13",
            "additionalProperty14": "14",
            "additionalProperty15": "15",
            "additionalProperty16": "16",
            "additionalProperty17": "17",
            "additionalProperty18": "18",
            "additionalProperty19": "19",
            "additionalProperty20": "20"
        },{
            "memberName": "Sammy",
            "callDate": "11/08/2015",
            "callerFirstName": "Denzel",
            "callerLastName": "Washington",
            "callerRelationship": "brother",
            "callStatus": "unsuccessfull",
            "callerPhoneNumber": "111-111-444",
            "callDuration": "0",
            "callType": "Any type",
            "anotherCallProperty": "info",
            "additionalProperty1": "1",
            "additionalProperty2": "2",
            "additionalProperty3": "3",
            "additionalProperty4": "4",
            "additionalProperty5": "5",
            "additionalProperty6": "6",
            "additionalProperty7": "7",
            "additionalProperty8": "8",
            "additionalProperty9": "9",
            "additionalProperty10": "10",
            "additionalProperty11": "11",
            "additionalProperty12": "12",
            "additionalProperty13": "13",
            "additionalProperty14": "14",
            "additionalProperty15": "15",
            "additionalProperty16": "16",
            "additionalProperty17": "17",
            "additionalProperty18": "18",
            "additionalProperty19": "19",
            "additionalProperty20": "20"
        },{
            "memberName": "Adam",
            "callDate": "11/11/2015",
            "callerFirstName": "Gene",
            "callerLastName": "Hackman",
            "callerRelationship": "brother",
            "callStatus": "successfull",
            "callerPhoneNumber": "111-111-111",
            "callDuration": "100",
            "callType": "Any type",
            "anotherCallProperty": "info",
            "additionalProperty1": "1",
            "additionalProperty2": "2",
            "additionalProperty3": "3",
            "additionalProperty4": "4",
            "additionalProperty5": "5",
            "additionalProperty6": "6",
            "additionalProperty7": "7",
            "additionalProperty8": "8",
            "additionalProperty9": "9",
            "additionalProperty10": "10",
            "additionalProperty11": "11",
            "additionalProperty12": "12",
            "additionalProperty13": "13",
            "additionalProperty14": "14",
            "additionalProperty15": "15",
            "additionalProperty16": "16",
            "additionalProperty17": "17",
            "additionalProperty18": "18",
            "additionalProperty19": "19",
            "additionalProperty20": "20"
        },{
            "memberName": "Rooney",
            "callDate": "11/11/2015",
            "callerFirstName": "Jeff",
            "callerLastName": "Bridges",
            "callerRelationship": "brother",
            "callStatus": "successfull",
            "callerPhoneNumber": "NUMBER",
            "callDuration": "100",
            "callType": "Any type",
            "anotherCallProperty": "info",
            "additionalProperty1": "1",
            "additionalProperty2": "2",
            "additionalProperty3": "3",
            "additionalProperty4": "4",
            "additionalProperty5": "5",
            "additionalProperty6": "6",
            "additionalProperty7": "7",
            "additionalProperty8": "8",
            "additionalProperty9": "9",
            "additionalProperty10": "10",
            "additionalProperty11": "11",
            "additionalProperty12": "12",
            "additionalProperty13": "13",
            "additionalProperty14": "14",
            "additionalProperty15": "15",
            "additionalProperty16": "16",
            "additionalProperty17": "17",
            "additionalProperty18": "18",
            "additionalProperty19": "19",
            "additionalProperty20": "20"
        },{
            "memberName": "Alex",
            "callDate": "05/11/2015",
            "callerFirstName": "Tim",
            "callerLastName": "Robins",
            "callerRelationship": "brother",
            "callStatus": "successfull",
            "callerPhoneNumber": "111-111-111",
            "callDuration": "100",
            "callType": "Any type",
            "anotherCallProperty": "info",
            "additionalProperty1": "1",
            "additionalProperty2": "2",
            "additionalProperty3": "3",
            "additionalProperty4": "4",
            "additionalProperty5": "5",
            "additionalProperty6": "6",
            "additionalProperty7": "7",
            "additionalProperty8": "8",
            "additionalProperty9": "9",
            "additionalProperty10": "10",
            "additionalProperty11": "11",
            "additionalProperty12": "12",
            "additionalProperty13": "13",
            "additionalProperty14": "14",
            "additionalProperty15": "15",
            "additionalProperty16": "16",
            "additionalProperty17": "17",
            "additionalProperty18": "18",
            "additionalProperty19": "19",
            "additionalProperty20": "20"
        },{
            "memberName": "Alexey",
            "callDate": "11/11/2015",
            "callerFirstName": "Henry",
            "callerLastName": "Fonda",
            "callerRelationship": "brother",
            "callStatus": "successfull",
            "callerPhoneNumber": "111-111-111",
            "callDuration": "100",
            "callType": "Any type",
            "anotherCallProperty": "info",
            "additionalProperty1": "1",
            "additionalProperty2": "2",
            "additionalProperty3": "3",
            "additionalProperty4": "4",
            "additionalProperty5": "5",
            "additionalProperty6": "6",
            "additionalProperty7": "7",
            "additionalProperty8": "8",
            "additionalProperty9": "9",
            "additionalProperty10": "10",
            "additionalProperty11": "11",
            "additionalProperty12": "12",
            "additionalProperty13": "13",
            "additionalProperty14": "14",
            "additionalProperty15": "15",
            "additionalProperty16": "16",
            "additionalProperty17": "17",
            "additionalProperty18": "18",
            "additionalProperty19": "19",
            "additionalProperty20": "20"
        },{
            "memberName": "Kelly",
            "callDate": "11/11/2015",
            "callerFirstName": "William",
            "callerLastName": "Hurt",
            "callerRelationship": "sister",
            "callStatus": "successfull",
            "callerPhoneNumber": "111-4345-111",
            "callDuration": "100",
            "callType": "Any type",
            "anotherCallProperty": "info",
            "additionalProperty1": "1",
            "additionalProperty2": "2",
            "additionalProperty3": "3",
            "additionalProperty4": "4",
            "additionalProperty5": "5",
            "additionalProperty6": "6",
            "additionalProperty7": "7",
            "additionalProperty8": "8",
            "additionalProperty9": "9",
            "additionalProperty10": "10",
            "additionalProperty11": "11",
            "additionalProperty12": "12",
            "additionalProperty13": "13",
            "additionalProperty14": "14",
            "additionalProperty15": "15",
            "additionalProperty16": "16",
            "additionalProperty17": "17",
            "additionalProperty18": "18",
            "additionalProperty19": "19",
            "additionalProperty20": "20"
        },{
            "memberName": "Zlatan",
            "callDate": "11/11/2015",
            "callerFirstName": "Kevin",
            "callerLastName": "Costner",
            "callerRelationship": "friend",
            "callStatus": "successfull",
            "callerPhoneNumber": "111-111-111",
            "callDuration": "100",
            "callType": "Any type",
            "anotherCallProperty": "info",
            "additionalProperty1": "1",
            "additionalProperty2": "2",
            "additionalProperty3": "3",
            "additionalProperty4": "4",
            "additionalProperty5": "5",
            "additionalProperty6": "6",
            "additionalProperty7": "7",
            "additionalProperty8": "8",
            "additionalProperty9": "9",
            "additionalProperty10": "10",
            "additionalProperty11": "11",
            "additionalProperty12": "12",
            "additionalProperty13": "13",
            "additionalProperty14": "14",
            "additionalProperty15": "15",
            "additionalProperty16": "16",
            "additionalProperty17": "17",
            "additionalProperty18": "18",
            "additionalProperty19": "19",
            "additionalProperty20": "20"
        },{
            "memberName": "Clint",
            "callDate": "11/11/2015",
            "callerFirstName": "Clint",
            "callerLastName": "Eastwood",
            "callerRelationship": "same",
            "callStatus": "successfull",
            "callerPhoneNumber": "111-111-111",
            "callDuration": "100",
            "callType": "Any type",
            "anotherCallProperty": "info",
            "additionalProperty1": "1",
            "additionalProperty2": "2",
            "additionalProperty3": "3",
            "additionalProperty4": "4",
            "additionalProperty5": "5",
            "additionalProperty6": "6",
            "additionalProperty7": "7",
            "additionalProperty8": "8",
            "additionalProperty9": "9",
            "additionalProperty10": "10",
            "additionalProperty11": "11",
            "additionalProperty12": "12",
            "additionalProperty13": "13",
            "additionalProperty14": "14",
            "additionalProperty15": "15",
            "additionalProperty16": "16",
            "additionalProperty17": "17",
            "additionalProperty18": "18",
            "additionalProperty19": "19",
            "additionalProperty20": "20"
        },{
            "memberName": "Santa Claus",
            "callDate": "11/11/2015",
            "callerFirstName": "Leonardo",
            "callerLastName": "DiCaprio",
            "callerRelationship": "grandpa",
            "callStatus": "successfull",
            "callerPhoneNumber": "111-111-111",
            "callDuration": "100",
            "callType": "Any type",
            "anotherCallProperty": "info",
            "additionalProperty1": "1",
            "additionalProperty2": "2",
            "additionalProperty3": "3",
            "additionalProperty4": "4",
            "additionalProperty5": "5",
            "additionalProperty6": "6",
            "additionalProperty7": "7",
            "additionalProperty8": "8",
            "additionalProperty9": "9",
            "additionalProperty10": "10",
            "additionalProperty11": "11",
            "additionalProperty12": "12",
            "additionalProperty13": "13",
            "additionalProperty14": "14",
            "additionalProperty15": "15",
            "additionalProperty16": "16",
            "additionalProperty17": "17",
            "additionalProperty18": "18",
            "additionalProperty19": "19",
            "additionalProperty20": "20"
        },{
            "memberName": "No name",
            "callDate": "11/11/2015",
            "callerFirstName": "Mel",
            "callerLastName": "Gibson",
            "callerRelationship": "brother",
            "callStatus": "successfull",
            "callerPhoneNumber": "111-111-111",
            "callDuration": "6787",
            "callType": "Any type",
            "anotherCallProperty": "info",
            "additionalProperty1": "1",
            "additionalProperty2": "2",
            "additionalProperty3": "3",
            "additionalProperty4": "4",
            "additionalProperty5": "5",
            "additionalProperty6": "6",
            "additionalProperty7": "7",
            "additionalProperty8": "8",
            "additionalProperty9": "9",
            "additionalProperty10": "10",
            "additionalProperty11": "11",
            "additionalProperty12": "12",
            "additionalProperty13": "13",
            "additionalProperty14": "14",
            "additionalProperty15": "15",
            "additionalProperty16": "16",
            "additionalProperty17": "17",
            "additionalProperty18": "18",
            "additionalProperty19": "19",
            "additionalProperty20": "20"
        }];

        

        var columnWidth = '150';
        var shortDataColmnDefs = [
            { field: 'memberName', width: columnWidth },
            { field: 'callDate', width: columnWidth},
            { field: 'callerFirstName', width: columnWidth},
            { field: 'callerLastName', width: columnWidth},
            { field: 'callerRelationship', width: columnWidth},
            { field: 'callStatus', width: columnWidth},
            { field: 'callerPhoneNumber', width: columnWidth},
            { field: 'callDuration', width: columnWidth},
            { field: 'callType', width: columnWidth},
            { field: 'anotherCallProperty', width: columnWidth},
        ];
        //
        var longDataColmnDefs = [
            { field: 'memberName', width: columnWidth },
            { field: 'callDate', width: columnWidth},
            { field: 'callerFirstName', width: columnWidth},
            { field: 'callerLastName', width: columnWidth},
            { field: 'callerRelationship', width: columnWidth},
            { field: 'callStatus', width: columnWidth},
            { field: 'callerPhoneNumber', width: columnWidth},
            { field: 'callDuration', width: columnWidth},
            { field: 'callType', width: columnWidth},
            { field: 'anotherCallProperty', width: columnWidth},
            { field: 'additionalProperty1', width: columnWidth},
            { field: 'additionalProperty2', width: columnWidth},
            { field: 'additionalProperty3', width: columnWidth},
            { field: 'additionalProperty4', width: columnWidth},
            { field: 'additionalProperty5', width: columnWidth},
            { field: 'additionalProperty6', width: columnWidth},
            { field: 'additionalProperty7', width: columnWidth},
            { field: 'additionalProperty8', width: columnWidth},
            { field: 'additionalProperty9', width: columnWidth},
            { field: 'additionalProperty10', width: columnWidth},
            { field: 'additionalProperty11', width: columnWidth},
            { field: 'additionalProperty12', width: columnWidth},
            { field: 'additionalProperty13', width: columnWidth},
            { field: 'additionalProperty14', width: columnWidth},
            { field: 'additionalProperty15', width: columnWidth},
            { field: 'additionalProperty16', width: columnWidth},
            { field: 'additionalProperty17', width: columnWidth},
            { field: 'additionalProperty18', width: columnWidth},
            { field: 'additionalProperty19', width: columnWidth},
            { field: 'additionalProperty20', width: columnWidth}
        ];

        $scope.showGrid = true;

        var gridOptions = {
            enableGridMenu: true,
            enablePagination: true,
            enablePaginationControls: true,
            paginationPageSizes: [5, 7, 9],
            paginationPageSize: 5
        };

        $scope.gridOptions = gridOptions;
        $scope.gridOptions.data = data;

        $scope.gridOptions = gridOptions;
        $scope.gridOptions.data = data;

        $scope.search = function(date) {
            debugger
            window.x = $scope.date;
        };

        $scope.reset = function(date) {
            //$scope.gridOptions.data = [];
            //$scope.showGrid = false;
        };

        $scope.getMockedData = function() {
            $scope.gridOptions = gridOptions;
            $scope.gridOptions.data = data;
            $scope.gridOptions.columnDefs = shortDataColmnDefs;
            $scope.showGrid = true;

            //dataProvider.getMembers().then(function(members) {
            //    $scope.members = members;
            //    $scope.gridOptions = gridOptions;
            //    $scope.gridOptions.data = members;
            //    $scope.gridOptions.columnDefs = shortDataColmnDefs;
            //    $scope.showGrid = true;
            //});
        };

        $scope.getMockedDataLong = function() {
            $scope.gridOptions = gridOptions;
            $scope.gridOptions.data = dataWithMoreProperties;
            $scope.gridOptions.columnDefs = longDataColmnDefs;
            $scope.showGrid = true;

            //dataProvider.getMoreMembers().then(function(members) {
            //    $scope.members = members;
            //    $scope.gridOptions = gridOptions;
            //    $scope.gridOptions.data = members;
            //    $scope.gridOptions.columnDefs = longDataColmnDefs;
            //    $scope.showGrid = true;
            //});
        };
    }
);